### PR TITLE
feat: add TemplateString support

### LINKED ISSUE #1: Does not work with Template strings
Marking: "banned.com" as a string to check, it doesn't throw a lint error if it is encapsulated in a Template string:

```ts
let normalString = "banned.com/site" // You should not use "banned.com".eslint(literal-check/literal-check)

let templateString = `banned.com/${"site"}` // No error
```

Plugin version: 

"eslint-plugin-literal-check": "^0.1.2",

### PR DESCRIPTION
**Pull request by charlie632**
- Renames `whiteList -> allowList` and `blackList -> denyList`
- Checks for the `TemplateElement` node to look for literals inside a Template String
- Added tests
Fixes #1

### CODE REVIEW

**Review by zisheng-ai — APPROVED** [review]
LGTM~

**Comment by youngjuning** [comment]
fix #1

**Comment by zisheng-ai** [comment]
@charlie632 Because NPM directly forced 2FA, my account could not be recovered. So I had no choice but to change my package name :(

**Comment by charlie632** [comment]
@youngjuning ohhh that's sad! What's the new package name?

**Comment by zisheng-ai** [comment]
@charlie632 eslint-plugin-literal-checker

**Comment by charlie632** [comment]
Thanks!

**Pull request merged**
